### ISSUE TITLE
Error trying to us login()

### ISSUE THREAD

**Issue by LilDinker** [cyberjunky/python-garminconnect#236]
Hi! I am running into an error trying to using the login function. I was using this function in this exact same way a few days ago, with no problem. Can't quite diagnose whats wrong.

```
from garminconnect import Garmin, GarminConnectConnectionError, GarminConnectTooManyRequestsError
<define email and password>

garmin = Garmin(correct_email, correct_password)
garmin.login()
```

Error:
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python312\Lib\site-packages\garminconnect\__init__.py", line 228, in login
    self.display_name = self.garth.profile["displayName"]
                        ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\garth\http.py", line 104, in profile
    assert isinstance(self._profile, dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

Versions:
```
Python 3.12.6
garminconnect==0.2.21
garth==0.4.46
```

OS: Windows

Any help would be greatly appreciated, thanks!

**Comment by LilDinker** [comment]
Closing because I see this is a duplicate issue
