### ISSUE TITLE
AttributeError: 'Garmin' object has no attribute 'download_activities'

### ISSUE THREAD

**Issue by Volker-brdb** [cyberjunky/python-garminconnect#98]
Hi,

choosing option
p -- Download activities data by date from '2022-10-30' to '2022-11-06'

I get following error
Executing: Download activities data by date from '2022-10-30' to '2022-11-06'

Traceback (most recent call last):
  File "<PATH>\example.py", line 377, in <module>
    switch(api, option)
  File "<PATH>\example.py", line 271, in switch
    display_json(f"api.download_activities({activity_id})", api.download_activities(activity_id))
                                                            ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Garmin' object has no attribute 'download_activities'. Did you mean: 'download_activity'?

**Comment by cyberjunky** [comment]
Hopefully fixed in version 0.1.49, thanks for reporting @Volker-brdb !

**Comment by Volker-brdb** [comment]
@cyberjunky  thx for the fast response.

Now I get following error

-------------------- api.download_activity(9928953063) --------------------
Traceback (most recent call last):
  File "<PATH>\example.py", line 397, in <module> switch(api, option)
  File "<PATH>\example.py", line 275, in switch display_json(f"api.download_activity({activity_id})", api.download_activity(activity_id))
  File "<PATH>\example.py", line 91, in display_json print(json.dumps(output, indent=4))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PATH>\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "<PATH>\Python\Python311\Lib\json\encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "<PATH>\Python\Python311\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "<PATH>\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
**TypeError: Object of type bytes is not JSON serializable**

**Comment by cyberjunky** [comment]
@Volker-brdb I believe I have fixed the example,py now, are you able to check?

**Comment by Volker-brdb** [comment]
@cyberjunky: download works now.....great!!
